<a href="https://colab.research.google.com/github/lisabroadhead/machine-learning/blob/main/lesson_notes_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# List

In [5]:
z = [1,2,3,45]
z, z[-1]

([1, 2, 3, 45], 45)

In [4]:
x = ["bunny", 9, 3.35,"sunny"]
x, x[1],x[2]

(['bunny', 9, 3.35, 'sunny'], 9, 3.35)

In [25]:
z[1] = "fish"
z, z[:1]


([1, 'fish', 3, 45], [1])

In [24]:
z.count(10)

0

# NumPy

In [37]:
price = [2,1,10]
type(price)

qty_sold = [17,40,1]
type(qty_sold)

# price * qty_sold

list

In [34]:
import numpy as np
price_arr = np.array(price)
qyt_arr = np.array(qty_sold)

type(price_arr), price_arr * qty_sold

(numpy.ndarray, array([34, 40, 10]))

In [39]:
cost_arr = np.array([.25,.50,5.00])
profit_arr = price_arr - cost_arr
print(profit_arr)
price_arr > 2.00

[1.75 0.5  5.  ]


array([False, False,  True])

In [48]:
# adding 

price_arr = np.append(price_arr, 7)
# price_arr = np.append(price_arr,[4.5,3,4,9])
# print(price_arr.dtype)

In [56]:
#deleting

price_arr = np.delete(price_arr,-1)
price_arr

array([ 2. ,  1. , 10. ,  7. ,  7. ,  4.5,  3. ,  4. ,  9. ,  7. ,  4.5,
        3. ,  4. ,  9. ,  7. ,  4.5,  3. ,  4. ,  9. ,  7. ,  7. ])

In [57]:
# replacing

price_arr[-1] = 14
price_arr

array([ 2. ,  1. , 10. ,  7. ,  7. ,  4.5,  3. ,  4. ,  9. ,  7. ,  4.5,
        3. ,  4. ,  9. ,  7. ,  4.5,  3. ,  4. ,  9. ,  7. , 14. ])