<a href="https://colab.research.google.com/github/lisabroadhead/machine-learning/blob/main/lesson_notes_may_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [8]:
filename = "/content/drive/MyDrive/Colab Notebooks/coding_dojo/week1/files/bostonHousing1978.csv"
df = pd.read_csv(filename)
df.head()


RM  LSTAT  PTRATIO  target
0  6.575   4.98     15.3    24.0
1  6.421   9.14     17.8    21.6
2  7.185   4.03     17.8    34.7
3  6.998   2.94     18.7    33.4
4  7.147   5.33     18.7    36.2

In [ ]:
df['name']
df[['name']]
df[['name','manufactros']]

In [ ]:
df.info()
df.shape()
len(def) # df short for datd frame
len(df.columns)

# NumPy
- pandas
- numpy
- mat
- sae

In [20]:
# can't decide what I wnt for dinner
dinner_options = ["cheese burges", "chicken Tikka Masala", "Filet Mingon", "Lasanga"]
np.random.choice(dinner_options)

'chicken Tikka Masala'

In [25]:
# calories per serving
cal_serving = np.array([740,240,408,301])
cal_serving

array([740, 240, 408, 301])

In [26]:
price = np.array([8.50,12.50,11,15.75])
price

array([ 8.5 , 12.5 , 11.  , 15.75])

In [27]:
servings = np.array([3,0,2,1])
servings

array([3, 0, 2, 1])

In [30]:
np.sum(servings * cal_serving)

3337

In [31]:
np.sum(servings * price)

63.25

In [33]:
# options array
options = np.array(["Cheeseburger", "Chicken Takki Masla","Lasanga","Filet Mingona"])
options

array(['Cheeseburger', 'Chicken Takki Masla', 'Lasanga', 'Filet Mingona'],
      dtype='<U19')

In [38]:
for i,food in enumerate(options):
  print(f"{i}: {food}")

0: Cheeseburger
1: Chicken Takki Masla
2: Lasanga
3: Filet Mingona


In [40]:
def index_report():
  for i,food in enumerate(options):
    print(f"{i}: {food}")

In [41]:
index_report()

0: Cheeseburger
1: Chicken Takki Masla
2: Lasanga
3: Filet Mingona


In [42]:
servings[1] = 2

In [45]:
servings

array([3, 2, 2, 1])

In [47]:
(servings * price).sum()

88.25

In [55]:
index_report()
discount = np.array([0.25,.0,0,0.25])
discount_price = price - price * discount
discount, discount_price

0: Cheeseburger
1: Chicken Takki Masla
2: Lasanga
3: Filet Mingona


(array([0.25, 0.  , 0.  , 0.25]), array([ 6.375 , 12.5   , 11.    , 11.8125]))

In [79]:
np.sum(discount_price)

41.6875

In [57]:
discount_price.round(2)

array([ 6.38, 12.5 , 11.  , 11.81])

In [58]:
np.sum(discount_price * servings)

77.9375

#Dictionary

In [69]:
dinner_data = {"dinner options": options,
               "Price" : price,
               "cal_serving": cal_serving,
               "Discount": discount,
               "Servings": servings
               }
dinner_data

{'Discount': array([0.25, 0.  , 0.  , 0.25]),
 'Price': array([ 8.5 , 12.5 , 11.  , 15.75]),
 'Servings': array([3, 2, 2, 1]),
 'cal_serving': array([740, 240, 408, 301]),
 'dinner options': array(['Cheeseburger', 'Chicken Takki Masla', 'Lasanga', 'Filet Mingona'],
       dtype='<U19')}

In [70]:
import pandas as pd

In [71]:
df = pd.DataFrame(dinner_data)
df

dinner options  Price  cal_serving  Discount  Servings
0         Cheeseburger   8.50          740      0.25         3
1  Chicken Takki Masla  12.50          240      0.00         2
2              Lasanga  11.00          408      0.00         2
3        Filet Mingona  15.75          301      0.25         1

In [76]:
# np.sum(df["Price"] - df["Price"] * df["Discount"]) * df["Servings"]
np.sum(df["Price"] - df["Price"] * df["Discount"]) 

41.6875

In [74]:
df["Servings"].sum()

8